import assert from 'node:assert/strict';import fs from 'node:fs';
const base='http://127.0.0.1:8787';const setupToken=JSON.parse(fs.readFileSync('.private/test-token.json','utf8')).token;const password='local-check-only-123456';
async function req(path,method='GET',body,token,origin='https://toyhebe-debug.github.io'){const r=await fetch(base+path,{method,headers:{Origin:origin,...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),headers:r.headers}}
assert.equal((await req('/api/family')).status,401);
assert.equal((await req('/api/auth/status')).data.configured,false);
assert.equal((await req('/api/auth/setup','POST',{password,setupToken:'0'.repeat(64)})).status,403);
const setup=await req('/api/auth/setup','POST',{password,setupToken});assert.equal(setup.status,200);const a=setup.data.token;assert.equal(a.length,64);
assert.equal((await req('/api/auth/setup','POST',{password,setupToken})).status,409);
assert.equal((await req('/api/auth/login','POST',{password:'wrong-password-1234'})).status,401);
const login=await req('/api/auth/login','POST',{password});assert.equal(login.status,200);const b=login.data.token;assert.notEqual(a,b);
const loaded=await req('/api/family','GET',undefined,a);assert.equal(loaded.status,200);
const packet={operationId:crypto.randomUUID(),baseVersion:loaded.data.version,data:structuredClone(loaded.data.data)};packet.data.stocks[0].amount=7;
const saved=await req('/api/family','PUT',packet,a);assert.equal(saved.status,200);
assert.equal((await req('/api/family','GET',undefined,b)).data.data.stocks[0].amount,7);
assert.equal((await req('/api/family','PUT',packet,a)).data.version,saved.data.version);
assert.equal((await req('/api/family','PUT',{...packet,operationId:crypto.randomUUID()},b)).status,409);
const valid={...packet,operationId:crypto.randomUUID(),baseVersion:saved.data.version};const invalid=structuredClone(valid);invalid.data.dueDate='2026-02-30';assert.equal((await req('/api/family','PUT',invalid,a)).status,400);
assert.equal((await req('/api/family','GET',undefined,a,'https://example.invalid')).status,403);
const pair=await Promise.all([req('/api/family','PUT',{...valid,operationId:crypto.randomUUID()},a),req('/api/family','PUT',{...valid,operationId:crypto.randomUUID()},b)]);assert.deepEqual(pair.map(r=>r.status).sort(),[200,409]);
// 清单首次保存、双设备读回、旧版页面写入及并发保护。
const prepModule=await import('../lib/preparation.ts');
const fresh=(await req('/api/family','GET',undefined,b)).data;
const preparation=prepModule.createPreparation();
preparation.items.find(i=>i.id==='pump').status='bought';
preparation.items.find(i=>i.id==='pump').packed=true;
const prepPacket={operationId:crypto.randomUUID(),baseVersion:fresh.version,data:{...fresh.data,preparation}};
const prepSave=await req('/api/family','PUT',prepPacket,b);assert.equal(prepSave.status,200);
const second=(await req('/api/family','GET',undefined,a)).data;
assert.equal(second.data.preparation.items.find(i=>i.id==='pump').packed,true);
const legacy=structuredClone(second.data);delete legacy.preparation;legacy.stocks[0].amount=9;
const legacySave=await req('/api/family','PUT',{operationId:crypto.randomUUID(),baseVersion:second.version,data:legacy},a);
assert.equal(legacySave.status,200);assert.deepEqual(legacySave.data.data.preparation,preparation);
assert.equal((await req('/api/family','GET',undefined,b)).data.data.stocks[0].amount,9);
const stale=await req('/api/family','PUT',{...prepPacket,operationId:crypto.randomUUID()},b);assert.equal(stale.status,409);assert.deepEqual(stale.data.latest.data.preparation,preparation);
const invalidPrep=structuredClone(legacySave.data.data);invalidPrep.preparation.items[0].packed=true;
assert.equal((await req('/api/family','PUT',{operationId:crypto.randomUUID(),baseVersion:legacySave.data.version,data:invalidPrep},b)).status,400);
// 香港采购与旧页面兼容：实际金额、确认事项、旧页面写入均保留。
const {hkFixture}=await import('./hk-fixture.ts');
const hkFresh=(await req('/api/family','GET',undefined,a)).data;
const hkTrip=hkFixture();hkTrip.items[0].status='已购';hkTrip.items[0].amount=42.5;hkTrip.items[0].currency='HKD';hkTrip.checks[0].done=true;
const hkSaved=await req('/api/family','PUT',{operationId:crypto.randomUUID(),baseVersion:hkFresh.version,data:{...hkFresh.data,hkTrip}},a);assert.equal(hkSaved.status,200);
const hkSecond=(await req('/api/family','GET',undefined,b)).data;assert.deepEqual(hkSecond.data.hkTrip,hkTrip);
const oldClient=structuredClone(hkSecond.data);delete oldClient.hkTrip;delete oldClient.preparation;
const keep=await req('/api/family','PUT',{operationId:crypto.randomUUID(),baseVersion:hkSecond.version,data:oldClient},b);assert.equal(keep.status,200);assert.deepEqual(keep.data.data.hkTrip,hkTrip);assert.deepEqual(keep.data.data.preparation,hkSecond.data.preparation);
const conflict=await req('/api/family','PUT',{operationId:crypto.randomUUID(),baseVersion:hkSecond.version,data:hkSecond.data},a);assert.equal(conflict.status,409);assert.deepEqual(conflict.data.latest.data.hkTrip,hkTrip);
assert.equal((await req('/api/auth/logout','POST',undefined,a)).status,200);
assert.equal((await req('/api/family','GET',undefined,a)).status,401);
assert.equal((await req('/api/family','GET',undefined,b)).status,200);
let limited=false;for(let i=0;i<10;i++){if((await req('/api/auth/login','POST',{password:'wrong-password-1234'})).status===429){limited=true;break}}assert.equal(limited,true);
console.log('PASS: setup secret, one-time setup, two-device login, unauthorized denial, shared persistence, idempotence, stale edits, validation, CORS, concurrent updates, logout isolation, login throttling, preparation shared readback, legacy preservation and stale-preparation conflict.');
