import {useState} from 'react';
import {ArrowLeft,ArrowUpRight,Check,ClipboardList,MapPin,Search,ShoppingBag,X,Wallet,Clock3} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {hkStatuses,hkSummary} from '@/lib/hk';
import type {HKItem,HKStatus,HKTrip} from '@/lib/hk';

type Props={trip:HKTrip|undefined;version:number;saving:boolean;onSave:(trip:HKTrip,version:number)=>Promise<boolean>;onBack:()=>void};
type Editor={kind:'item';item:HKItem;version:number}|{kind:'check';id:string;label:string;note:string;version:number};
const money=(n:number)=>n.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function HKProcurement({trip,version,saving,onSave,onBack}:Props){
 const [section,setSection]=useState('list'),[filter,setFilter]=useState('pending'),[query,setQuery]=useState('');
 const [editor,setEditor]=useState<Editor|null>(null),[error,setError]=useState('');
 if(!trip)return <section className="hk-page"><button className="text-button" onClick={onBack}><ArrowLeft size={17}/>返回小助手</button><h1>香港采购</h1><p className="empty-text">采购资料还未载入。请稍后重新同步。</p></section>;
 const totals=hkSummary(trip.items);
 const items=trip.items.filter(i=>(filter==='all'||filter==='pending'?(filter==='all'||(i.status!=='已购'&&i.status!=='取消')):i.status===filter)&&[i.id,i.name,i.model,i.region,i.note].join(' ').toLowerCase().includes(query.toLowerCase()));
 const completedChecks=trip.checks.filter(c=>c.done).length;
 function editItem(item:HKItem){setError('');setEditor({kind:'item',item:structuredClone(item),version})}
 async function bought(item:HKItem){if(trip)await onSave({...trip,items:trip.items.map(i=>i.id===item.id?{...i,status:'已购'}:i)},version)}
 async function check(id:string,done:boolean){if(trip)await onSave({...trip,checks:trip.checks.map(c=>c.id===id?{...c,done}:c)},version)}
 async function submit(e:React.FormEvent<HTMLFormElement>){
  e.preventDefault();if(!editor||!trip||saving)return;setError('');
  if(editor.version!==version){setError('另一台设备更新了记录。当前输入还在，请关闭后重新打开这项再改。');return}
  const f=new FormData(e.currentTarget),str=(key:string)=>String(f.get(key)||'').trim();
  let updated=trip;
  if(editor.kind==='item'){
   const quantity=str('quantity')===''?null:Number(str('quantity')),amount=str('amount')===''?null:Number(str('amount'));
   const currency=(str('currency')||null) as HKItem['currency'];
   if(quantity!==null&&(!Number.isFinite(quantity)||quantity<=0||quantity>10000)){setError('实际数量填大于 0 的数，未知可以留空。');return}
   if(amount!==null&&(!Number.isFinite(amount)||amount<0||!currency||Math.abs(amount*100-Math.round(amount*100))>0.000001)){setError('请填写有效金额（最多两位小数）并选择币种；未知可以留空。');return}
   const item:HKItem={...editor.item,status:str('status') as HKStatus,actualQuantity:quantity,amount,currency,actualModel:str('actualModel'),store:str('store'),note:str('note')};
   updated={...trip,items:trip.items.map(i=>i.id===item.id?item:i)};
  }else updated={...trip,checks:trip.checks.map(c=>c.id===editor.id?{...c,note:str('note')}:c)};
  if(await onSave(updated,editor.version))setEditor(null);else setError('这次还没保存，输入仍保留。请查看同步提示后重试。');
 }
 function sourceLinks(ids:string[]){return <div className="hk-source-links">{ids.map(id=>{const s=trip?.sources.find(x=>x.id===id);return s?<a key={id} href={s.url} target="_blank" rel="noreferrer">{s.title}<ArrowUpRight size={12}/></a>:null})}</div>}
 return <section className="hk-page">
  <button className="text-button hk-back" onClick={onBack}><ArrowLeft size={17}/>返回小助手</button>
  <header className="hk-hero"><p className="eyebrow">{trip.date.replaceAll('-',' / ')} · 出门采购</p><div className="hk-title"><h1>{trip.title}</h1><ShoppingBag size={32}/></div><p>{trip.routeSummary}</p><div className="hk-summary"><strong>{totals.bought}<small> / {totals.total}</small></strong><span>项已购<br/><small>还有 {totals.pending} 项待处理</small></span><span className="hk-private">两人共用记录</span></div><div className="prep-meter"><i style={{width:(totals.total?totals.bought/totals.total*100:0)+'%'}}/></div></header>
  <div className="hk-cutoffs">{trip.milestones.slice(0,2).map(m=><div key={m.label}><Clock3 size={16}/><strong>{m.time}</strong><span>{m.label}</span></div>)}</div>
  <p className="hk-plan-note">上方时间为规划目标；票务、预约和门店现货仍需确认。具体安排见“当天路线”。</p>
  <nav className="hk-sections" aria-label="香港采购内容">{[['list','采购清单'],['route','当天路线'],['stores','门店'],['checks','出发前']].map(([key,label])=><button key={key} aria-pressed={section===key} onClick={()=>setSection(key)}>{label}</button>)}</nav>
  {section==='list'&&<>
   <div className="hk-spend"><div><Wallet size={18}/><span>已购金额</span></div><strong>HK$ {totals.totals.HKD===null?'—':money(totals.totals.HKD)}<span>¥ {totals.totals.CNY===null?'—':money(totals.totals.CNY)}</span></strong><small>{totals.unpriced?`${totals.unpriced} 项已购还没记完整金额。`:'只汇总已购且已填金额的记录。'}空白表示未记录，不是预算为零；币种分开算。</small></div>
   <label className="prep-search"><Search size={17}/><input aria-label="搜索香港采购" placeholder="搜物品、型号或备注" value={query} onChange={e=>setQuery(e.target.value)}/></label>
   <div className="prep-filters hk-filters" aria-label="采购状态筛选">{[['pending','待处理'],['all','全部'],['已购','已购'],['缺货','缺货'],['重复待确认','重复待确认'],['暂缓','暂缓'],['取消','取消']].map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div>
   <div className="hk-items">{items.map(item=><article className={'hk-item '+(item.status==='已购'?'is-bought':'')} key={item.id}><div className="hk-item-top"><span className="hk-id">{item.id}</span><span className={'hk-status '+(item.status==='已购'?'bought':item.status==='重复待确认'?'repeat':'')}>{item.status}</span></div><h2>{item.name}</h2><p className="hk-model">{item.model}</p><div className="hk-item-meta"><span>{item.suggested}</span><span>{item.region}</span></div><p className="hk-check">{item.check}</p>{(item.note||item.actualQuantity!==null||item.amount!==null||item.actualModel||item.store)&&<div className="hk-record">{item.actualModel&&<p>实际型号：{item.actualModel}</p>}{item.actualQuantity!==null&&<p>实购数量：{item.actualQuantity}</p>}{item.amount!==null&&<p>记录金额：{item.currency==='HKD'?'HK$':'¥'} {money(item.amount)}</p>}{item.store&&<p>购买门店：{item.store}</p>}{item.note&&<p>{item.note}</p>}</div>}<div className="hk-item-actions"><button className="secondary" onClick={()=>editItem(item)} disabled={saving}><ClipboardList size={16}/>记数量 / 花费</button>{item.status!=='已购'&&item.status!=='取消'&&<button className="primary" onClick={()=>bought(item)} disabled={saving}><Check size={16}/>已买到</button>}</div><details className="hk-item-source"><summary>选择依据与资料</summary><p>{item.origin} · 文件记录</p>{sourceLinks(item.sourceIds)}</details></article>)}</div>
   {!items.length&&<div className="prep-empty"><Check size={25}/><p>{query?'没有找到这件物品。':'这个分类已经看完了。'}</p><button className="text-button" onClick={()=>{setFilter('all');setQuery('')}}>查看全部</button></div>}
   <details className="hk-fold"><summary>已有库存与本次不买</summary><p className="section-note">这些是文件中的盘点记录，不计入本次已购。</p>{trip.inventory.map(i=><article className="hk-inventory" key={i.id}><small>{i.id} · {i.status}</small><h3>{i.name}</h3><p>{i.quantity}</p><p>{i.note}</p></article>)}</details>
   <details className="hk-fold"><summary>使用前要核对的事</summary>{trip.notes.filter(n=>!['步行与换乘','K11 仅作替换点','不绕行旺角与沙田','这次行程仍有哪些待确认'].includes(n.title)).map(n=><article className="hk-note" key={n.title}><h3>{n.title}</h3><p>{n.body}</p>{sourceLinks(n.sourceIds)}</article>)}</details>
  </>}
  {section==='route'&&<><div className="hk-route-intro"><h2>当天行程</h2><p>按文件的假设时段展示。车次窗口和航班截图不是已订订单；如签约延后，删减购物，保留返程余量。</p></div><ol className="hk-timeline">{trip.route.map((step,index)=><li key={index}><span className="hk-step-dot"/><div><time>{step.time}</time><h3>{step.title}</h3><p>{step.note}</p></div></li>)}</ol>{trip.notes.filter(n=>['步行与换乘','K11 仅作替换点','不绕行旺角与沙田','这次行程仍有哪些待确认'].includes(n.title)).map(n=><details className="hk-fold" key={n.title}><summary>{n.title}</summary><div className="hk-note"><p>{n.body}</p>{sourceLinks(n.sourceIds)}</div></details>)}</>}
  {section==='stores'&&<><p className="section-note">主线只安排一家金店、一家万宁、一家母婴集合店。以下地址与常规时间来自文件快照，未确认当天现货；备选用于替换，不逐家巡店。</p>{[[true,'主线门店'],[false,'备选与不采用']] .map(([primary,label])=><section key={String(primary)}><h2 className="hk-section-title">{String(label)}</h2><div className="hk-store-grid">{trip.stores.filter(s=>s.primary===primary).map(s=><article className="hk-store" key={s.id}><small>{s.id} · {s.excluded?'本次不去':s.primary?'主线候选':'就近替换'}</small><h3>{s.name}</h3><p><MapPin size={15}/>{s.address}</p><p><Clock3 size={15}/>{s.hours}</p><p>{s.contact}</p><div className="hk-store-role">{s.role}</div><div className="hk-store-links"><a href={'https://maps.apple.com/?q='+encodeURIComponent(s.name+' '+s.address)} target="_blank" rel="noreferrer">地图查看<ArrowUpRight size={15}/></a>{s.url&&<a href={s.url} target="_blank" rel="noreferrer">官方资料<ArrowUpRight size={15}/></a>}</div></article>)}</div></section>)}</>}
  {section==='checks'&&<><div className="hk-checks-heading"><h2>出发前与收货确认</h2><span>{completedChecks} / {trip.checks.length} 已确认</span></div><p className="section-note">实际办妥后再勾选。可记确认的时间、地点或结果；这里不会发送消息或代订票。</p><div className="hk-check-list">{trip.checks.map(c=><article key={c.id} className={c.done?'done':''}><label><input type="checkbox" checked={c.done} disabled={saving} onChange={e=>check(c.id,e.target.checked)}/><span>{c.label}</span></label>{c.note&&<p>{c.note}</p>}<button className="text-button" onClick={()=>{setError('');setEditor({kind:'check',id:c.id,label:c.label,note:c.note,version})}}>记确认结果</button></article>)}</div></>}
  <p className="hk-provenance">来源：你提供的行程文件 v{trip.sourceVersion} · {trip.snapshotDate} 快照。采购数量不代表使用剂量；本页进度不自动改变待产包。</p>
  <Dialog open={!!editor} onOpenChange={open=>{if(!open&&!saving)setEditor(null)}}><DialogContent className="family-dialog" showCloseButton={false}><DialogClose className="dialog-close" aria-label="关闭" disabled={saving}><X size={20}/></DialogClose><DialogTitle>{editor?.kind==='item'?editor.item.name:'记确认结果'}</DialogTitle><DialogDescription>{editor?.kind==='item'?'实际买到什么就记什么，未知金额和数量可以留空。':editor?.label}</DialogDescription>{editor&&<form className="edit-form" key={editor.kind==='item'?editor.item.id:editor.id} onSubmit={submit}>{editor.kind==='item'&&<><label>采购状态<select name="status" defaultValue={editor.item.status}>{hkStatuses.map(s=><option key={s}>{s}</option>)}</select></label><label>实际买到的型号 / 规格<input name="actualModel" maxLength={200} defaultValue={editor.item.actualModel} placeholder={editor.item.model}/></label><label>实购数量<input name="quantity" type="number" inputMode="decimal" step="any" min="0.01" max="10000" defaultValue={editor.item.actualQuantity??''} placeholder="未知留空"/><small>建议：{editor.item.suggested}。这里只记采购量，不是使用剂量。</small></label><div className="form-row"><label>本项实付总金额<input name="amount" type="number" inputMode="decimal" step="0.01" min="0" max="10000000" defaultValue={editor.item.amount??''} placeholder="未知留空"/></label><label>币种<select name="currency" defaultValue={editor.item.currency??''}><option value="">请选择</option><option value="HKD">港币 HKD</option><option value="CNY">人民币 CNY</option></select></label></div><label>实际门店<input name="store" maxLength={200} defaultValue={editor.item.store} placeholder="店名或地址"/></label></>}<label>{editor.kind==='item'?'备注':'确认结果'}<textarea name="note" rows={3} maxLength={2000} defaultValue={editor.kind==='item'?editor.item.note:editor.note} placeholder={editor.kind==='item'?'缺货、替代规格、存放位置等':'确认了什么、何时确认；无需填写证件号码'}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary save-button" disabled={saving}>{saving?'正在保存…':'保存'}</button></form>}</DialogContent></Dialog>
 </section>;
}
